services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
        POSTGRES_DB: food_ordering
        POSTGRES_USER: food_ordering
        POSTGRES_PASSWORD: Pass@word
        PGDATA: /data/food_ordering
    volumes:
      - db:/data/food_ordering
    ports:
      - 5332:5432
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: